version: '3'
services:
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: maddevs_internship
      MYSQL_ROOT_PASSWORD: mensetmanus90 
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '4306:3306'
  php:
    build: .
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache
      - ./:/app
    ports:
      - '8000:80'
    links: 
      - mysql